'use strict';

angular.module('netRankApp')
  .service('rankService', function () {

    function rankService() {
      this.someData_ = [{
        "SECTOR": "1",
        "STABBR": "AL",
        "CHFTITLE": "President",
        "FAXTELE": "2563725030",
        "CBSATYPE": "1",
        "LOCALE": "12",
        "MEDICAL": "2",
        "APPLURL": "www.aamu.edu/Admissions/apply/Pages/default.aspx",
        "CARNEGIE": "16",
        "OBEREG": "5",
        "CBSA": "26620",
        "NEWID": "-2",
        "ACT": "A ",
        "CCSIZSET": "14",
        "LANDGRNT": "1",
        "UGOFFER": "1",
        "OPEFLAG": "1",
        "CONTROL": "1",
        "WEBADDR": "www.aamu.edu/",
        "INSTSIZE": "3",
        "CYACTIVE": "1",
        "GROFFER": "1",
        "HLOFFER": "9",
        "HOSPITAL": "2",
        "ICLEVEL": "1",
        "CLOSEDAT": "2014-09-02T00:00:00",
        "FAIDURL": "www.aamu.edu/Admissions/fincialaid/Pages/default.aspx",
        "INSTNM": "Alabama A & M University",
        "HDEGOFR1": "12",
        "LONGITUD": "-86.568502",
        "DEGGRANT": "1",
        "EIN": "636001109",
        "NECTA": "-2",
        "CCIPGRAD": "18",
        "HBCU": "1",
        "ZIP": "35762",
        "GENTELE": "2563725000",
        "ADMINURL": "www.aamu.edu/admissions/pages/default.aspx",
        "COUNTYNM": "Madison County",
        "F1SYSNAM": " ",
        "CHFNM": "Dr. Andrew Hugine, Jr.",
        "CSA": "290",
        "COUNTYCD": "1089",
        "IALIAS": "AAMU",
        "F1SYSCOD": "-2",
        "CCBASIC": "18",
        "FIPS": "1",
        "UNITID": "100654",
        "INSTCAT": "2",
        "OPEID": "100200",
        "PSEFLAG": "1",
        "POSTSEC": "1",
        "NPRICURL": "galileo.aamu.edu/netpricecalculator/npcalc.htm",
        "CITY": "Normal",
        "OPENPUBL": "1",
        "ADDR": "4900 Meridian Street",
        "F1SYSTYP": "2",
        "TRIBAL": "2",
        "CCENRPRF": "4",
        "DEATHYR": "-2",
        "RPTMTH": "1",
        "CCUGPROF": "9",
        "LATITUDE": "34.783368",
        "PSET4FLG": "1",
        "CNGDSTCD": "105",
        "_id": 1,
        "CCIPUG": "13"
      }, {
        "SECTOR": "1",
        "STABBR": "AL",
        "CHFTITLE": "President",
        "FAXTELE": "2059757114",
        "CBSATYPE": "1",
        "LOCALE": "12",
        "MEDICAL": "1",
        "APPLURL": "ssb.it.uab.edu/pls/sctprod/zsapk003_ug_web_appl.create_page",
        "CARNEGIE": "15",
        "OBEREG": "5",
        "CBSA": "13820",
        "NEWID": "-2",
        "ACT": "A ",
        "CCSIZSET": "15",
        "LANDGRNT": "2",
        "UGOFFER": "1",
        "OPEFLAG": "1",
        "CONTROL": "1",
        "WEBADDR": "www.uab.edu",
        "INSTSIZE": "4",
        "CYACTIVE": "1",
        "GROFFER": "1",
        "HLOFFER": "9",
        "HOSPITAL": "1",
        "ICLEVEL": "1",
        "CLOSEDAT": "2014-09-02T00:00:00",
        "FAIDURL": "www.uab.edu/students/paying-for-college",
        "INSTNM": "University of Alabama at Birmingham",
        "HDEGOFR1": "11",
        "LONGITUD": "-86.809170",
        "DEGGRANT": "1",
        "EIN": "636005396",
        "NECTA": "-2",
        "CCIPGRAD": "17",
        "HBCU": "2",
        "ZIP": "35294-0110",
        "GENTELE": "2059344011",
        "ADMINURL": "www.uab.edu/students/undergraduate-admissions",
        "COUNTYNM": "Jefferson County",
        "F1SYSNAM": "The University of Alabama System",
        "CHFNM": "Ray L. Watts",
        "CSA": "142",
        "COUNTYCD": "1073",
        "IALIAS": " ",
        "F1SYSCOD": "101050",
        "CCBASIC": "15",
        "FIPS": "1",
        "UNITID": "100663",
        "INSTCAT": "2",
        "OPEID": "105200",
        "PSEFLAG": "1",
        "POSTSEC": "1",
        "NPRICURL": "www.collegeportraits.org/AL/UAB/estimator/agree",
        "CITY": "Birmingham",
        "OPENPUBL": "1",
        "ADDR": "Administration Bldg Suite 1070",
        "F1SYSTYP": "1",
        "TRIBAL": "2",
        "CCENRPRF": "5",
        "DEATHYR": "-2",
        "RPTMTH": "1",
        "CCUGPROF": "8",
        "LATITUDE": "33.502230",
        "PSET4FLG": "1",
        "CNGDSTCD": "107",
        "_id": 2,
        "CCIPUG": "11"
      }, {
        "SECTOR": "2",
        "STABBR": "AL",
        "CHFTITLE": "President",
        "FAXTELE": "3343873878",
        "CBSATYPE": "1",
        "LOCALE": "12",
        "MEDICAL": "2",
        "APPLURL": "https://www.amridgeuniversity.edu/Amridge/login.aspx?ReturnUrl=%2fAmridge%2fStudent%2fFormChoice.aspx",
        "CARNEGIE": "51",
        "OBEREG": "5",
        "CBSA": "33860",
        "NEWID": "-2",
        "ACT": "A ",
        "CCSIZSET": "6",
        "LANDGRNT": "2",
        "UGOFFER": "1",
        "OPEFLAG": "1",
        "CONTROL": "2",
        "WEBADDR": "www.amridgeuniversity.edu",
        "INSTSIZE": "1",
        "CYACTIVE": "1",
        "GROFFER": "1",
        "HLOFFER": "9",
        "HOSPITAL": "2",
        "ICLEVEL": "1",
        "CLOSEDAT": "2014-09-02T00:00:00",
        "FAIDURL": "www.amridgeuniversity.edu/au_financialaid.html",
        "INSTNM": "Amridge University",
        "HDEGOFR1": "11",
        "LONGITUD": "-86.174010",
        "DEGGRANT": "1",
        "EIN": "237034324",
        "NECTA": "-2",
        "CCIPGRAD": "13",
        "HBCU": "2",
        "ZIP": "36117-3553",
        "GENTELE": "33438770007528",
        "ADMINURL": "www.amridgeuniversity.edu/au_admissions.html",
        "COUNTYNM": "Montgomery County",
        "F1SYSNAM": " ",
        "CHFNM": "Michael Turner",
        "CSA": "-2",
        "COUNTYCD": "1101",
        "IALIAS": "Southern Christian University |Regions University",
        "F1SYSCOD": "-2",
        "CCBASIC": "21",
        "FIPS": "1",
        "UNITID": "100690",
        "INSTCAT": "2",
        "OPEID": "2503400",
        "PSEFLAG": "1",
        "POSTSEC": "1",
        "NPRICURL": "tcc.noellevitz.com/(S(miwoihs5stz5cpyifh4nczu0))/Amridge%20University/Freshman-Students",
        "CITY": "Montgomery",
        "OPENPUBL": "1",
        "ADDR": "1200 Taylor Rd",
        "F1SYSTYP": "2",
        "TRIBAL": "2",
        "CCENRPRF": "5",
        "DEATHYR": "-2",
        "RPTMTH": "1",
        "CCUGPROF": "6",
        "LATITUDE": "32.362609",
        "PSET4FLG": "1",
        "CNGDSTCD": "102",
        "_id": 3,
        "CCIPUG": "11"
      }, {
        "SECTOR": "1",
        "STABBR": "AL",
        "CHFTITLE": "President",
        "FAXTELE": " ",
        "CBSATYPE": "1",
        "LOCALE": "12",
        "MEDICAL": "2",
        "APPLURL": "register.uah.edu",
        "CARNEGIE": "16",
        "OBEREG": "5",
        "CBSA": "26620",
        "NEWID": "-2",
        "ACT": "A ",
        "CCSIZSET": "12",
        "LANDGRNT": "2",
        "UGOFFER": "1",
        "OPEFLAG": "1",
        "CONTROL": "1",
        "WEBADDR": "www.uah.edu",
        "INSTSIZE": "3",
        "CYACTIVE": "1",
        "GROFFER": "1",
        "HLOFFER": "9",
        "HOSPITAL": "2",
        "ICLEVEL": "1",
        "CLOSEDAT": "2014-09-02T00:00:00",
        "FAIDURL": "finaid.uah.edu/",
        "INSTNM": "University of Alabama in Huntsville",
        "HDEGOFR1": "11",
        "LONGITUD": "-86.638420",
        "DEGGRANT": "1",
        "EIN": "630520830",
        "NECTA": "-2",
        "CCIPGRAD": "17",
        "HBCU": "2",
        "ZIP": "35899",
        "GENTELE": "2568246120",
        "ADMINURL": "admissions.uah.edu/",
        "COUNTYNM": "Madison County",
        "F1SYSNAM": "The University of Alabama System",
        "CHFNM": "Robert A. Altenkirch",
        "CSA": "290",
        "COUNTYCD": "1089",
        "IALIAS": "UAH |University of Alabama Huntsville",
        "F1SYSCOD": "101050",
        "CCBASIC": "15",
        "FIPS": "1",
        "UNITID": "100706",
        "INSTCAT": "2",
        "OPEID": "105500",
        "PSEFLAG": "1",
        "POSTSEC": "1",
        "NPRICURL": "finaid.uah.edu/",
        "CITY": "Huntsville",
        "OPENPUBL": "1",
        "ADDR": "301 Sparkman Dr",
        "F1SYSTYP": "1",
        "TRIBAL": "2",
        "CCENRPRF": "4",
        "DEATHYR": "-2",
        "RPTMTH": "1",
        "CCUGPROF": "8",
        "LATITUDE": "34.722818",
        "PSET4FLG": "1",
        "CNGDSTCD": "105",
        "_id": 4,
        "CCIPUG": "14"
      }, {
        "SECTOR": "1",
        "STABBR": "AL",
        "CHFTITLE": "President",
        "FAXTELE": "3348346861",
        "CBSATYPE": "1",
        "LOCALE": "12",
        "MEDICAL": "2",
        "APPLURL": "psadmin.alasu.edu:8501/psp/paprd_1/EMPLOYEE/HRMS/c/ASU_SS_NONID_MENU.ASU_SS_ONL_SECURE.GBL?PORTALPARAM_PTCNAV=ASU_LK_ONLINEAPP&EOPP.SCNode=EMP",
        "CARNEGIE": "21",
        "OBEREG": "5",
        "CBSA": "33860",
        "NEWID": "-2",
        "ACT": "A ",
        "CCSIZSET": "13",
        "LANDGRNT": "2",
        "UGOFFER": "1",
        "OPEFLAG": "1",
        "CONTROL": "1",
        "WEBADDR": "www.alasu.edu/email/index.aspx",
        "INSTSIZE": "3",
        "CYACTIVE": "1",
        "GROFFER": "1",
        "HLOFFER": "9",
        "HOSPITAL": "2",
        "ICLEVEL": "1",
        "CLOSEDAT": "2014-09-02T00:00:00",
        "FAIDURL": "www.alasu.edu/cost-aid/index.aspx/",
        "INSTNM": "Alabama State University",
        "HDEGOFR1": "11",
        "LONGITUD": "-86.295677",
        "DEGGRANT": "1",
        "EIN": "636001101",
        "NECTA": "-2",
        "CCIPGRAD": "12",
        "HBCU": "1",
        "ZIP": "36104-0271",
        "GENTELE": "3342294400",
        "ADMINURL": "www.alasu.edu/admissions/index.aspx",
        "COUNTYNM": "Montgomery County",
        "F1SYSNAM": " ",
        "CHFNM": "Gwen Boyd",
        "CSA": "-2",
        "COUNTYCD": "1101",
        "IALIAS": " ",
        "F1SYSCOD": "-2",
        "CCBASIC": "18",
        "FIPS": "1",
        "UNITID": "100724",
        "INSTCAT": "2",
        "OPEID": "100500",
        "PSEFLAG": "1",
        "POSTSEC": "1",
        "NPRICURL": "www.alasu.edu/cost-aid/forms/calculator/index.aspx/",
        "CITY": "Montgomery",
        "OPENPUBL": "1",
        "ADDR": "915 S Jackson Street",
        "F1SYSTYP": "2",
        "TRIBAL": "2",
        "CCENRPRF": "4",
        "DEATHYR": "-2",
        "RPTMTH": "1",
        "CCUGPROF": "9",
        "LATITUDE": "32.364317",
        "PSET4FLG": "1",
        "CNGDSTCD": "107",
        "_id": 5,
        "CCIPUG": "10"
      }];
      
    }

    rankService.prototype.getAllData = function() {
      return this.someData_;
    };


    return new rankService();

  });
